import type { Metadata } from 'next'
import './globals.css'
import Topbar from '../components/Common/Topbar'

export const metadata: Metadata = {
  title: 'SEOUL COLLECTIVE',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className="block">
        <Topbar />
        <div className="pt-32">{children}</div>
      </body>
    </html>
  )
}
