import type { Metadata } from 'next'
import './globals.css'
import Topbar from '../components/Common/Topbar'
import Footer from '../components/Common/Footer'
import localFont from 'next/font/local'

export const metadata: Metadata = {
  title: 'SEOUL COLLECTIVE',
  description: 'Generated by create next app',
}

const futuraBold = localFont({
  src: '../../public/fonts/FuturaLT-Bold.woff2',
  variable: '--font-futura-bold',
  display: 'swap',
})

const futura = localFont({
  src: '../../public/fonts/FuturaLT.woff2',
  variable: '--font-futura',
  display: 'swap',
})

const poppins = localFont({
  src: '../../public/fonts/Poppins-Medium.ttf',
  variable: '--font-poppins',
  display: 'swap',
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className={`${futuraBold.variable} ${futura.variable} ${poppins.variable}`}>
      <body className="flex min-h-screen flex-col">
        <Topbar />
        <main className="mx-auto flex-1 px-[5.375rem] pt-[10rem]">{children}</main>
        <Footer />
      </body>
    </html>
  )
}
