import type { Metadata } from 'next'
import './globals.css'
import Topbar from '../components/Common/Topbar'
import Footer from '../components/Common/Footer'
import localFont from 'next/font/local'
import { Providers } from './providers'

export const metadata: Metadata = {
  title: 'SEOUL COLLECTIVE',
  description: 'Generated by create next app',
}

const gothamBlack = localFont({
  src: '../../public/fonts/Gotham-Black.ttf',
  variable: '--font-gotham-black',
  display: 'swap',
})

const gothamBold = localFont({
  src: '../../public/fonts/Gotham-Bold.ttf',
  variable: '--font-gotham-bold',
  display: 'swap',
})

const gothamMedium = localFont({
  src: '../../public/fonts/Gotham-Medium.ttf',
  variable: '--font-gotham-medium',
  display: 'swap',
})

const terminaHeavy = localFont({
  src: '../../public/fonts/Termina-Heavy.otf',
  variable: '--font-termina-heavy',
  display: 'swap',
})

const neuehaasBlackItalic = localFont({
  src: '../../public/fonts/Neue_Haas_Unica_W1G_Black_Italic.otf',
  variable: '--font-nh-black-italic',
  display: 'swap',
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html
      lang="en"
      className={`${gothamBlack.variable} ${gothamBold.variable} ${gothamMedium.variable} ${terminaHeavy.variable} ${neuehaasBlackItalic.variable}`}
    >
      {/* 두 폰트 variable 모두 추가 */}
      <body className="flex min-h-screen flex-col">
        <Providers>
          <Topbar />
          <main className="mx-auto flex-1 px-[5.375rem] pt-[15rem]">{children}</main>
          <Footer />
        </Providers>
      </body>
    </html>
  )
}
